---
- name: Testing playbook to push to github
  hosts: localhost
  tasks:
    - name: Debugging task
      ansible.builtin.debug:
        msg: The {{ inventory_hostname }} belongs to {{ ansible_facts['os_family'] }}
