---

- name: "Create the directories where the lvm would be mounted:"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{  mount_points }}"
  tags:
    - checks

- name: Ensure blivet Python library and all libblockdev plugins are installed
  ansible.builtin.dnf:
    name:
      - python3-blivet
      - lvm2
      - libblockdev-crypto
      - libblockdev-dm
      - libblockdev-fs
      - libblockdev-loop
      - libblockdev-lvm
      - libblockdev-mdraid
      - libblockdev-mpath
      - libblockdev-nvdimm
      - libblockdev-nvme
      - libblockdev-part
      - libblockdev-swap
    state: present
  tags:
    - checks

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ host_name }}"
  tags:
    - checks

- name: Check forward DNS
  ansible.builtin.command: "getent hosts {{ ansible_fqdn }}"
  register: forward_dns
  changed_when: false
  failed_when: forward_dns.rc != 0
  tags:
    - checks

- name: Ensure satellite server  /etc/hosts has IPv4 static entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: ".*{{ ansible_fqdn }}"
    line: "{{ ansible_default_ipv4.address }}   {{ ansible_fqdn }} {{ ansible_hostname }}"
    state: present
  tags:
    - checks

- name: Ensure /etc/hosts has IPv4 static entry of the satellite server  on localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: ".*{{ hostvars[inventory_hostname].ansible_fqdn }}"
    line: "{{ hostvars[inventory_hostname]. ansible_default_ipv4.address }} {{ hostvars[inventory_hostname].ansible_hostname }} {{ hostvars[inventory_hostname].ansible_fqdn }}"
    state: present
  delegate_to: localhost
  run_once: true
  tags:
    - checks

- name: Check reverse DNS
  ansible.builtin.command: "getent hosts {{ ansible_default_ipv4.address }}"
  register: reverse_dns
  changed_when: false
  failed_when: reverse_dns.rc != 0
  tags:
    - checks
