---
- name: Create series of logical volumes for the satellite server on vgsat
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.storage
  vars:
    storage_pools:
      - name: vgsat
        disks:
          - "{{ selected_disk }}"
        type: lvm
        grow_to_fill: true
        volumes:
          - name: log_lv
            fs_type: xfs
            size: "10g"
            mount_point: "/var/log"
            state: present

          - name: pgsql_lv
            fs_type: xfs
            size: "20g"
            mount_point: "/var/lib/pgsql"
            state: present

          - name: puppet_lv
            fs_type: xfs
            size: "1g"
            mount_point: "/opt/puppetlabs"
            state: present
         
          - name: pulp_lv
            fs_type: xfs
            size: "100%FREE"
            mount_point: "/var/lib/pulp"
            state: present

       ####    The below lvm is only required if you're enabling Red Hat Lightspeed in Satellite
              #  - name: containers_lv                 
              #  fs_type: xfs
              #  size: "***"                                 
              #  mount_point: "/var/lib/containers"
              #   state: present
  when: selected_disk is defined
  tags:
    - lvm


