---

- name: Ensure firewalld and its Python binding are installed
  ansible.builtin.dnf:
    name:
      - firewalld
      - python3-firewall
    state: present
  tags:
    - firewalld

- name: Ensure firewalld service is running and enabled at boot
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  tags:
    - firewalld

- name: Open the ports for clients on Satellite Server
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ ports }}"
  tags:
    - firewalld

- name: Allow access to services on Satellite Server
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ services }}"
  notify: reload the firewalld daemon
  tags:
    - firewalld

- name: View all firewall zones and allowed services
  ansible.builtin.command: firewall-cmd --list-all
  register: firewalld
  tags:
    - firewalld

- name: Debug firewall zones and allowed services
  ansible.builtin.debug:
    msg: "{{ firewalld.stdout_lines | select('search', '^\\s*services:') | list }}"
  tags:
    - firewalld

- name: Ensure that the host name and local host resolve correctly
  ansible.builtin.ping:
  register: pingout
  tags:
    - firewalld

- name: Debug host name and local host resolve correctly
  ansible.builtin.debug:
    var: pingout
  tags:
    - firewalld

- name: Ensure host resolves again
  ansible.builtin.shell: ping -c1 `hostname -f`
  register: resolves
  tags:
    - firewalld

- name: Debug host resolves
  ansible.builtin.debug:
    var: resolves
  tags:
    - firewalld

- name: Ensure SELinux is enabled
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Check current system locale
  ansible.builtin.command: localectl status
  register: locale_status
  changed_when: false
  check_mode: no

- name: Show current locale
  ansible.builtin.debug:
    msg: "{{ locale_status.stdout }}"

- name: Set system locale to en_US.UTF-8
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
  become: yes
  when: "'LANG=en_US.UTF-8' not in locale_status.stdout"

- name: Confirm locale is set
  ansible.builtin.debug:
    msg: "✅ Locale set to en_US.UTF-8"
