---
- name: Import manifest
  ansible.builtin.import_role:
  name:  redhat.satellite.manifest
  tags:
  - manifest
  delegate_to: localhost
  run_once: true

- name: Add repositories
  ansible.builtin.import_role:
    name: redhat.satellite.repositories
    satellite_products:
      - name: Red Hat Enterprise Linux for x86_64
        repository_sets:
          - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
            releasever: 8
          - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
            releasever: 8
          - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
            releasever: 9
          - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
            releasever: 9
          - name: Red Hat Enterprise Linux 10 for x86_64 - AppStream (RPMs)
            releasever: 10
          - name: Red Hat Enterprise Linux 10 for x86_64 - BaseOS (RPMs)
            releasever: 10
          - name: Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)
          - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)
          - name: Red Hat Satellite Client 6 for RHEL 10 x86_64 (RPMs)
  tags:
    - repos

- name: Sync the added repos from the previous task
  redhat.satellite.repository_sync:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    product: Red Hat Enterprise Linux for x86_64
  tags:
    - repos

- name: Create a sync plan for the repos
  ansible.builtin.import_role:
    name: redhat.satellite.sync_plans
  vars:
    satellite_sync_plans:
      - name: Rhel Daily sync
        interval: daily
        sync_date: "2025-12-02 03:00:00"
        products:
          - Red Hat Enterprise Linux for x86_64
  tags:
    - repos

  name: Create lifecycle Environments
  ansible.builtin.import_role:
   name: redhat.satellite.lifecycle_environments
  vars:
   satellite_lifecycle_environments:
     - name: "Dev"
       prior: "Library"
     - name: "QA"
       prior: "Dev"
     - name: "Prod"
       prior: "QA"

- name: Create content views and composite content views
  ansible.builtin.import_role:
    name: redhat.satellite.content_views
  vars:
    satellite_content_views:
      - name: cv_rhel8
        repositories:
          - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs
            product: 'Red Hat Enterprise Linux for x86_64'
      - name: cv_rhel9
        repositories:
          - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
            product: 'Red Hat Enterprise Linux for x86_64'
      - name: cv_rhel10
        repositories:
          - name: Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10
            product: 'Red Hat Enterprise Linux for x86_64'
          - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
            product: 'Red Hat Enterprise Linux for x86_64'
      - name: ccv_rhel8
        auto_publish: true
        components:
          - content_view: cv_rhel8
            latest: true
      - name: ccv_rhel9
        auto_publish: true
        components:
          - content_view: cv_rhel9
            latest: true
      - name: ccv_rhel10
        auto_publish: true
        components:
          - content_view: cv_rhel10
            latest: true
  tags:
      - content_views

- name: Publish content views
  ansible.builtin.import_role:
    name: redhat.satellite.content_view_publish
  vars:
    satellite_content_views:
      - cv_rhel8
      - cv_rhel9
      - cv_rhel10

- name: "Publish the composite content view and promote that version"
  redhat.satellite.content_view_version:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    content_view: "{{ item }}"
    lifecycle_environments:
      - Dev
      - Prod
  loop:
    - ccv_rhel8
    - ccv_rhel9
    - ccv_rhel10
  tags:
    - promote
  
- name: Create activation keys
  ansible.builtin.import_role:
    name: redhat.satellite.activation_keys
  vars:
    satellite_activation_keys:
      - name: "ak-rhel8"
        lifecycle_environment: "Prod"
        content_view: "ccv_rhel8"
        content_overrides:
          - label: satellite-client-6-for-rhel-8-x86_64-rpms
            override: enabled

      - name: "ak-rhel9"
        lifecycle_environment: "Prod"
        content_view: "ccv_rhel9"
        content_overrides:
          - label: satellite-client-6-for-rhel-9-x86_64-rpms
            override: enabled
      - name: "ak-rhel10"
        lifecycle_environment: "Prod"
        content_view: "ccv_rhel10"
        content_overrides:
          - label: Red Hat Satellite Client 6 for RHEL 10 x86_64 RPMs
            override: enable
  tags:
    - ak-activation_keys 